name: Deploy with release

on:
  push:
    branches:
      - production

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - uses: rymndhng/release-on-push-action@master
        with:
          tag_prefix: "v"
          bump_version_scheme: minor
